Add HierarchicalNSW::indexFileSize() function for precise memory footprint control
nmslib/hnswlib pull request #427
Opened 2022-12-05 17:57 UTC by drons

2023-01-22 00:12 UTC, yurymalkov commented
Hi @drons,
Thank for the PR! We will check it and merge it after we prepare the release (should happen soon).

2023-05-07 11:38 UTC, dyashuni commented on python_bindings/bindings.cpp
> +    void indexFileSize() const {
we need to return an index size here
```cpp
size_t indexFileSize() const {
    return appr_alg->indexFileSize();
}
```

2023-05-07 11:40 UTC, dyashuni requested changes
Thank you, please add a small change

2023-05-07 14:01 UTC, drons commented on python_bindings/bindings.cpp
> +    void indexFileSize() const {
:man_facepalming:

2023-05-13 05:00 UTC, yurymalkov approved these changes

2023-05-13 05:00 UTC, yurymalkov commented
Thank you for the PR!

2023-05-13 05:01 UTC, merged

2023-05-13 09:00 UTC, drons commented
Thanks!